# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

# use the ubuntu vm for testing
pool:
  vmImage: 'ubuntu-latest'

# use a variable to specify the release configuration
variables:
  buildConfiguration: 'Release'

# get the correct version of dot net core
steps:
- task: UseDotNet@2
  inputs:
    version: '3.1.x'

# run dotnet build for Dapper.SuaveExtensions
- task: DotNetCoreCLI@2
  inputs:
    command: build
    projects: '**/Dapper.SuaveExtensions.csproj'
    arguments:  '--configuration $(buildConfiguration)'

# run dotnet build for Dapper.SuaveExtensions.Tests
- task: DotNetCoreCLI@2
  inputs:
    command: build
    projects: '**/Dapper.SuaveExtensions.Tests.csproj'
    arguments:  '--configuration $(buildConfiguration)'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      
      Get-ChildItem -Path $(Build.Repository.LocalPath) –Recurse

# explicitly copy mdf/ldf files into correct location
#- task: CopyFiles@2
#  inputs:
#    SourceFolder: ''
#    Contents: '*.(mdf|ldf)'
#    TargetFolder: '$(Build.ArtefactStagingDirectory)'

# run dotnet test for all test projects
#- task: DotNetCoreCLI@2
#  inputs:
#    command: test
#    projects: '**/*Tests/*.csproj'
#    arguments: '--configuration $(buildConfiguration) --no-build'
