# Package and Deploy Pipeline

trigger:
- none

# use the Ubuntu vm for build / package / deploy
pool:
  vmImage: 'ubuntu-latest'

# use a variable to specify the release configuration
variables:
  buildConfiguration: 'Release'

# get the correct version of dot net core
steps:
- task: UseDotNet@2
  inputs:
    version: '3.1.x'

# run dotnet build for the Dapper.SuaveExtensions project
- task: DotNetCoreCLI@2
  inputs:
    command: build
    projects: '**/Dapper.SuaveExtensions.csproj'
    arguments:  '--configuration $(buildConfiguration)'

# run dotnet pack to build .nupkg
- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: '**/Dapper.SuaveExtensions.csproj'
    nobuild: true
    versioningScheme: 'off'

# publish the .nupkg as a build artifact
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: nuget

# publish the build artifact to nuget.org
# dotnet nuget push AppLogger.1.0.0.nupkg -k qz2jga8pl3dvn2akksyquwcs9ygggg4exypy3bhxy6w6x6 -s https://api.nuget.org/v3/index.json